services:
  frigate-export:
    build: .
    image: henhouse/frigate-export:1.1.0
    volumes:
      - ./downloads:/app/downloads
      - ./output_logs:/app/output_logs
    environment:
      - FRIGATE_SERVER=${FRIGATE_SERVER:-http://192.168.1.81:5000/api/events}
      - MONGODB_IP=${MONGODB_IP:-192.168.1.81}
      - MONGODB_PORT=${MONGODB_PORT}
      - MONGODB_NAME=${MONGODB_NAME}
      - MONGODB_COLLECTION=${MONGODB_COLLECTION}
      - MQTT_TOPICS=${MQTT_TOPICS}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - MQTT_PORT=${MQTT_PORT}
      - MQTT_BROKER=${MQTT_BROKER}
      - DOWNLOADS_DIR=/app/downloads
      - PROCESS_VIDEO=${PROCESS_VIDEO:-false}
      - LOGS_DIR=${LOGS_DIR}
      - CRON_SCHEDULE=${CRON_SCHEDULE:-0 * * * *}
      - LOOP_DELAY_SECONDS=${LOOP_DELAY_SECONDS}
    restart: unless-stopped
    depends_on:
      - mongodb
    networks:
      - frigate-network

  mongodb:
    image: mongo:latest # Or specify a specific version like mongo:7.0
    container_name: frigate-mongodb
    ports:
      - "27017:27017" # Map host port 27017 to container port 27017
    volumes:
      - ./mongodb_data:/data/db # Persist data using a named volume
    # environment:
      # Optional: Set MongoDB root user and password for authentication
      # - MONGO_INITDB_ROOT_USERNAME=admin
      # - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped # Restart the container automatically unless explicitly stopped
    networks:
      - frigate-network

networks:
  frigate-network:
    driver: bridge

volumes:
  mongodb_data: # Define the named volume for data persistence